### ISSUE TITLE
Segmentation fault on Pop!_OS when running the app

### ISSUE THREAD

**Issue by Vexcited** [gdm-settings/gdm-settings#196] opened 2023-10-17 06:49 UTC
### What happened?

```console
/tmp/.mount_Login_fceFoF/AppRun: line 8: 84327 Segmentation fault      (core dumped) gdm-settings "$@"
```

### Expected behavior

App launches with no segmentation fault

### To Reproduce

Run the app using the AppImage or the Flatpak on Pop!_OS

### Application Version

3.1, 3.0, also tried the 4.0 in Releases tab

### Format/Source

AppImage, Flatpak

### Environment

- **OS**: Pop!_OS 22.04
- **GNOME**: 42.9

**Comment by realmazharhussain** [comment] 2023-10-17 10:43
> ```
> /tmp/.mount_Login_fceFoF/AppRun: line 8: 84327 Segmentation fault      (core dumped) gdm-settings "$@"
> ```

This is the error as produced by the AppImage. What error does the flatpak give?

**Comment by rome-legacy** [comment] 2024-02-07 20:39
Hi, 
same problem on Ubuntu 22.04.3, Gnome 42.9
Trying to run AppImage v4.1 with the same error

I do not use flatpak, so i cannot give an answer to that

kind regards
rome

**Comment by realmazharhussain** [comment] 2024-05-23 16:13
Closing as duplicate of #209. Subscribe to #209 in order to get notified about updates.

**Closed by realmazharhussain** 2024-05-23 16:13 UTC
Labels: bug
