### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by wabu06** [gdm-settings/gdm-settings#185] opened 2023-09-25 07:09 UTC
### What happened?

Segmentation fault (core dumped),  when the ABOUT selection is made from the drop down menu

### Expected behavior

na

### To Reproduce

na

### Application Version

3.3-1

### Format/Source

deb package from debian repo

### Environment

- **OS**: Debian GNU/Linux trixie/sid x86_64
- **GNOME**: Cinnamon 5.6.8

**Comment by realmazharhussain** [comment] 2023-10-03 03:07
This seems to be an issue with [AppStreamGlib](https://people.freedesktop.org/~hughsient/appstream-glib). It is a library this app uses to generate "What's New" section of the "About" window.

I haven't reported the issue upstream because I cannot reproduce it outside of my app. Once I have a reliable description with steps to reproduce the issue, I'll report it upstream.

Until then, the workaround is to uninstall `appstream-glib` package if nothing else depends on it. Alternatively, you could ask Debian maintainers to disable that feature temporarily. The patch needed for that is given below

```diff
diff --git a/src/about.py b/src/about.py
index 876af47..0347e1f 100644
--- a/src/about.py
+++ b/src/about.py
@@ -112,9 +112,4 @@ def about_window(win):
         translator_credits = _("translator-credits"),
         )
 
-    fetcher = ReleaseNotesFetcher()
-    flags = GObject.BindingFlags.SYNC_CREATE;
-    fetcher.bind_property("notes", abt, "release-notes", flags)
-    fetcher.bind_property("version", abt, "release-notes-version", flags)
-
     return abt
```

Use the patch command with `-V none -p1` options in order to apply the patch.

**Comment by realmazharhussain** [comment] 2024-05-23 16:17
This was fixed a long time ago. Forgot to close the issue tracker. So, doing it now.

**Closed by realmazharhussain** 2024-05-23 16:17 UTC
Labels: bug
