### ISSUE TITLE
Can't use Appimage file V4.1 with Fedora 39 because of missing library.

### ISSUE THREAD

**Issue by Tuxman2** [gdm-settings/gdm-settings#208] opened 2023-11-12 10:23 UTC
### What happened?

Hello,

I tried to launch the v4.1 appimage version under Fedora 39. The problem is the 4.1 appimage version use libtiff 4.5.0 or libtiff 4.6.0 version (need libtiff.so.6). Fedora 39 use libtiff 4.4.0 version (libtiff.so.5 or libtiff.so.5.8.0). Via terminal, I launched the appimage file and I received the following warning message : "Failed to load shared library 'libgdk_pixbuf-2.0.so.0' referenced by the typelib: libtiff.so.6 : cannot open shared object file : no such file or directory." libtiff 4.5.0 is available for Fedora 40 or rawhide but not for Fedora 39. It seems that libtiff 4.5.0 and libtiff 4.6.0 have libtiff.so.6 file.

### Expected behavior

Be able to launch V4.1 version of appimage under Fedora 39.

### To Reproduce

See what happened.

### Application Version

gdm-setting 4.1

### Format/Source

Appimage

### Environment

Fedora 39

**Comment by realmazharhussain** [comment] 2023-11-12 10:41
4 out of 14 currently open issues are bug reports about the AppImage not launching. The AppImage build system/scripts need a complete revamp.

**Comment by Tuxman2** [comment] 2023-11-12 10:46
Ok. I have some problem with flatpack version, so I installed manually gdm-setting from source. But I prefer an appimage version.

When do you thing a good appimage version will be available ?

Thanks.

Regards

**Comment by realmazharhussain** [comment] 2023-11-12 12:02
Probably not soon. I have opened a [new issue](https://github.com/gdm-settings/gdm-settings/issues/209) to track revamped AppImage support. You can subscribe to it if you want to get notified when the revamped AppImage support is added.

**Comment by realmazharhussain** [comment] 2024-05-23 16:11
Closing as duplicate of https://github.com/gdm-settings/gdm-settings/issues/209.

**Closed by realmazharhussain** 2024-05-23 16:11 UTC
Labels: bug
