### ISSUE TITLE
Unable to apply wallpaper

### ISSUE THREAD

**Issue by orowith2os** [gdm-settings/gdm-settings#183] opened 2023-09-23 01:47 UTC
### What happened?

When attempting to set a wallpaper, the terminal will complain of a TypeError and the GUI will fail with no indication of what happened.

### Expected behavior

The background was set successfully.

### To Reproduce

- Run Fedora (Silverblue). I'm on Rawhide.
- Select a background.
- Hit Apply.

### Detailed Explanation (Optional)

Here's the output from the terminal:

```
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/gdm_settings/lib/background_task.py", line 26, in <lambda>
    finish_callback = lambda self, task, nothing: self.finish_callback()
                                                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/gdm_settings/window.py", line 136, in on_apply_finished
    if self.apply_task.finish():
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/gdm_settings/lib/background_task.py", line 51, in finish
    raise value
  File "/app/lib/python3.11/site-packages/gdm_settings/lib/background_task.py", line 36, in _thread_cb
    retval = self.function()
             ^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/gdm_settings/settings.py", line 569, in apply_settings
    self.apply_shell_theme_settings()
  File "/app/lib/python3.11/site-packages/gdm_settings/settings.py", line 338, in apply_shell_theme_settings
    self.backup_default_shell_theme()
  File "/app/lib/python3.11/site-packages/gdm_settings/settings.py", line 322, in backup_default_shell_theme
    gr_utils.extract_default_theme(f'{env.TEMP_DIR}/default-pure')
  File "/app/lib/python3.11/site-packages/gdm_settings/gr_utils.py", line 67, in extract_default_theme
    resource_list = lib.get_stdout(["gresource", "list", env.HOST_ROOT + gresource_file]).splitlines()
                                                         ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
```

The `gresource` command appears to be missing, and most likely is why this issue is occurring. gdm-settings should notify the user of this on startup to ensure issues like this can be caught before they become relevant.

### Application Version

3.3

### Format/Source

Flatpak

### Environment

- **Firmware Version:**                            N1GETA9W (1.88 )
- **OS Name:**                                     Fedora Linux Rawhide.20230922.n.0 (Silverblue Prerelease)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.0
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.6.0-0.rc2.20230921git42dc814987c1.22.fc40.x86_64

**Comment by orowith2os** [comment] 2023-09-23 02:05
Installing `glib2-devel` for the `gresource` command gives the same output.

**Comment by orowith2os** [comment] 2023-09-23 02:11
`gdm-devel` and still nothing.

**Comment by orowith2os** [comment] 2023-09-23 02:25
Maybe the problem is it's attempting to run `gresource` from the Flatpak env, and not on the host?

**Comment by realmazharhussain** [comment] 2023-09-23 02:32
This issue has already been resolved with https://github.com/gdm-settings/gdm-settings/commit/c5209cac4a5b2fb5a0c8db6453c501e36b16d317. It will be included in the next major release. The workaround is to reinstall gnome-shell or gnome-shell-common package.

**Comment by orowith2os** [comment] 2023-09-23 04:11
Not quite sure if I'd call that "resolved". This command should run successfully for it to override the background, right?

```
gresource list /usr/share/gnome-shell/gnome-shell-theme.gresource
```

**Comment by realmazharhussain** [comment] 2023-09-23 04:26
> This command should run successfully for it to override the background, right?
> 
> ```
> gresource list /usr/share/gnome-shell/gnome-shell-theme.gresource
> ```

Actually, no. This app needs the unmodified/original default gnome-shell-theme.gresource file to work. The above error happens when it cannot find such gresource file.

In other words, at least one of the following commands should print nothing when run.

```bash
gresource list /usr/share/gnome-shell/gnome-shell-theme.gresource /org/gnome/shell/theme/custom-theme
```

```bash
gresource list /usr/share/gnome-shell/gnome-shell-theme.gresource.default /org/gnome/shell/theme/custom-theme
```

**Comment by orowith2os** [comment] 2023-09-23 05:21
Non-default works for me, with nothing printed. The default one doesn't exist.

**Comment by orowith2os** [comment] 2023-09-23 05:43
I'm still thinking this is some problem related to the Flatpak sandbox not being worked around properly. The resource file exists, and the command should be fine. But I don't think it's actually running the command on the host.

**Comment by realmazharhussain** [comment] 2023-09-24 05:09
> Non-default works for me, with nothing printed. The default one doesn't exist.

In that case, it might be sandbox issue as you suggested. Does the app have appropriate permissions? What is the output of the following command?

```bash
flatpak info --show-permissions io.github.realmazharhussain.GdmSettings
```

**Comment by orowith2os** [comment] 2023-09-24 05:16
```
[Context]
shared=ipc;
sockets=x11;wayland;fallback-x11;
devices=dri;
filesystems=host-etc;host-os;xdg-config/monitors.xml:ro;

[Session Bus Policy]
org.freedesktop.Flatpak=talk
```

Nothing seems out of place. Is it running the gresource command in the Flatpak env, as I suspect, and thus not working properly? Would that be a factor?

**Comment by realmazharhussain** [comment] 2023-09-24 05:36
The gresource command is available inside the flatpak sandbox and the app has access to gnome-shell-theme.gresource file. So, there is no reason to run the command outside the sandbox.

> ```
>     resource_list = lib.get_stdout(["gresource", "list", env.HOST_ROOT + gresource_file]).splitlines()
>                                                          ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
> TypeError: can only concatenate str (not "NoneType") to str
> ```

As you can see from the error message, the problem is not that gresource command is not available, the problem is that value of `gresource_file` variable is `None`. `gresource_file` is `None` only when the app could not detect an unmodifed version of gnome-shell-theme.gresource file.

What does the app print on the terminal if you run it with `-v` option?

**Comment by orowith2os** [comment] 2023-09-24 05:40
```
INFO: Application Version    = 3.3
INFO: Operating System       = Fedora Linux Rawhide.20230922.n.0 (Silverblue Prerelease)
INFO: PackageType            = Flatpak
INFO: TEMP_DIR               = /run/user/1000/app/io.github.realmazharhussain.GdmSettings
INFO: HOST_DATA_DIRS         = /usr/local/share:/usr/share
INFO: ShellGresourceFile     = /usr/share/gnome-shell/gnome-shell-theme.gresource
INFO: UbuntuGdmGresourceFile = None
INFO: pkexec version 123
```

Could it be attempting to utilize the UbuntuGdmGresourceFile? *That* is None.

**Comment by realmazharhussain** [comment] 2023-09-24 05:45
No, there is another value that does not get printed in gdm-settings 3.3 but does in the latest development version. That value is probably None. I'll post a flatpak.zip file of the latest development version in a minute.

**Comment by realmazharhussain** [comment] 2023-09-24 05:50
[gdm-settings.flatpak.zip](https://github.com/gdm-settings/gdm-settings/files/12707886/gdm-settings.flatpak.zip)

If you run this flatpak via `flatpak run io.github.realmazharhussain.GdmSettings//master -v` command, what does it output?

**Comment by orowith2os** [comment] 2023-09-24 06:01
Minor nit: now would probably be a good time to upgrade to the GNOME 45 runtime. 

And it outputs this:

```
INFO:gdms.gui: Application Version    = 4.alpha
INFO:gdms.gui: Operating System       = Fedora Linux Rawhide.20230922.n.0 (Silverblue Prerelease)
INFO:gdms.gui: PackageType            = Flatpak
INFO:gdms.gui: TEMP_DIR               = /run/user/1000/app/io.github.realmazharhussain.GdmSettings
INFO:gdms.gui: HOST_DATA_DIRS         = /usr/local/share:/usr/share
INFO:gdms.gui: ShellGresourceFile     = /usr/share/gnome-shell/gnome-shell-theme.gresource
INFO:gdms.gui: UbuntuGdmGresourceFile = None
INFO:gdms.gui: Default Gresource File = None
INFO:gdms.gui: pkexec version 123
```

**Comment by realmazharhussain** [comment] 2023-09-24 06:10
> Minor nit: now would probably be a good time to upgrade to the GNOME 45 runtime.

I already did. The version of gdm-settings that is on Flathub is using the latest GNOME runtime. It's just that I use a cellular network and it is acting up lately. So, I cannot install the 45 Sdk right now.

> ```
> INFO:gdms.gui: Default Gresource File = None
> ```

This is what I was talking about. You did reinstall `gnome-shell` and `gnome-shell-common` packages, right?

**Comment by orowith2os** [comment] 2023-09-24 06:16
Fedora only has the `gnome-shell` package.

**Comment by realmazharhussain** [comment] 2023-09-24 06:19
So, did you reinstall it or did you not?

**Comment by orowith2os** [comment] 2023-09-24 06:20
I'm running a clean base image, and the files are unmodified by design. Nothing *to* reinstall, if I could.

**Comment by realmazharhussain** [comment] 2023-09-24 06:22
```bash
flatpak run --command=gresource io.github.realmazharhussain.GdmSettings list /run/host/usr/share/gnome-shell/gnome-shell-theme.gresource
```

What does this command print?

**Comment by orowith2os** [comment] 2023-09-24 06:23
```
oro@fedora ~> flatpak run --command=gresource io.github.realmazharhussain.GdmSettings list /run/host/usr/share/gnome-shell/gnome-shell-theme.gresource
/org/gnome/shell/theme/calendar-today-light.svg
/org/gnome/shell/theme/calendar-today.svg
/org/gnome/shell/theme/checkbox-focused.svg
/org/gnome/shell/theme/checkbox-off-focused-light.svg
/org/gnome/shell/theme/checkbox-off-focused.svg
/org/gnome/shell/theme/checkbox-off-light.svg
/org/gnome/shell/theme/checkbox-off.svg
/org/gnome/shell/theme/checkbox.svg
/org/gnome/shell/theme/gnome-shell-dark.css
/org/gnome/shell/theme/gnome-shell-high-contrast.css
/org/gnome/shell/theme/gnome-shell-light.css
/org/gnome/shell/theme/gnome-shell-start.svg
/org/gnome/shell/theme/pad-osd.css
/org/gnome/shell/theme/process-working.svg
/org/gnome/shell/theme/toggle-off-hc.svg
/org/gnome/shell/theme/toggle-off-light.svg
/org/gnome/shell/theme/toggle-off.svg
/org/gnome/shell/theme/toggle-on-hc.svg
/org/gnome/shell/theme/toggle-on-light.svg
/org/gnome/shell/theme/toggle-on.svg
/org/gnome/shell/theme/workspace-placeholder.svg
```

**Comment by realmazharhussain** [comment] 2023-09-24 06:27
OK, I see they have renamed `/org/gnome/shell/theme/gnome-shell.css` to `/org/gnome/shell/theme/gnome-shell-dark.css`. I'll have to add proper support for this and it'll take some time.

**Comment by realmazharhussain** [comment] 2023-09-24 06:49
Since this turned out to be an entirely different issue, I have opened [a new, more appropriate issue tracker](https://github.com/gdm-settings/gdm-settings/issues/184) for it. If you would like to receive updates on the issue, subscribe to that issue tracker.

Closing this one in favor of #184. The discussion will continue there.

**Closed by realmazharhussain** 2023-09-24 06:49 UTC
Labels: bug
