### ISSUE TITLE
Writing error in OSTREE systems!

### ISSUE THREAD

**Issue by swyknox** [gdm-settings/gdm-settings#220] opened 2024-01-11 22:56 UTC
### What happened?

When trying to apply/save changes to the system, I receive the following error:
```
cp: could not create common file '/usr/share/gnome-shell/gnome-shell-theme.gresource.default': Read-only file system
```

### Expected behavior

The changes should be applied to the system without problems.

### To Reproduce

In an OSTREE system (in my case, FEDORA Silverblue 39), after defining the options, click on "apply" so that the changes can take effect, that is, they are saved in the system.
![image](https://github.com/gdm-settings/gdm-settings/assets/52772425/feebb955-9699-4e05-b0f8-af376b9a1c5d)

### Detailed Explanation (Optional)
I know that Silverblue is a read-only system, however, I opened this issue because previously it was possible to change the GDM settings in Silverblue through gdm-settings without any problems!

### Application Version

4.1

### Format/Source

Flatpak

### Environment

- **OS**: Fedora Silverblue 39
- **GNOME**: 45.3

**Comment by tsilvs** [comment] 2024-02-06 12:26
Experiencing the same thing. Is it possible to work around it by writing settings to GDM user directory or `/etc/gdm` instead of `/usr/var` directory?

**Comment by realmazharhussain** [comment] 2024-02-06 14:39
Some settings are written to `/etc` while some had to be applied by modifying `/usr/share/gnome-shell/gnome-shell-theme.gresource` file. With how the app currently stores settings, all of them have to be applied together. That is why writing to `/usr` could not be avoided till now.

However, GDM supports extensions now, and we could possibly leverage `user-theme` extension instead of writing directly to `/usr`. Also, since recently, systemd has a `systemd-sysext` utility, and we could leverage that as well.

There is some hope on this front.

**Comment by realmazharhussain** [comment] 2024-02-06 14:40
By the way, I am closing this as a duplicate of #172. Further discussion should happen there.

**Closed** 2024-02-06 14:40 UTC
Labels: bug
