### ISSUE TITLE
symbol lookup error: /tmp/.mount_GDM_SercdIqA/usr/lib/libc.so.6: undefined symbol: __tunable_is_initialized, version GLIBC_PRIVATE

### ISSUE THREAD

**Issue by Zorono** [gdm-settings/gdm-settings#264] opened 2024-10-24 11:01 UTC
### What happened?

it failed to run on my Ubuntu **22.04.5** due to some kind of **incompatibility** with **libc**

### Expected behavior

it was expected to get opened

### To Reproduce

try to run gdm-settings AppImage on **Ubuntu 22.04.5 LTS**

### Application Version

4.4

### Format/Source

AppImage

### Environment

- **OS**:  Ubuntu 22.04.5
- **GNOME**:  42.9

**Comment by realmazharhussain** [comment] 2024-11-14 15:29
Duplicate of #209.

**Closed by realmazharhussain** 2024-11-14 15:29 UTC
Labels: bug
